# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-01 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_fields'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fields',
            new_name='Field',
        ),
    ]
