# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20181101_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Project'),
        ),
    ]
