# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_field_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='fields',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.Field'),
        ),
    ]
